### PR TITLE
update HESEL documentation

### PR DESCRIPTION
**Pull request by Thrysoe**

### CODE REVIEW

**Comment by kosl** [comment]
Thanks. Please check the build.

**Comment by Thrysoe** [comment]
I can see that the build fails. I can build it just fine locally though. Any suggestions @kosl ?

**Comment by kosl** [comment]
Log https://wpcd-workflows.github.io/sphinx.log <https://wpcd-workflows.github.io/sphinx.log> is clean. Apparently the old one :( and not the one that failed.
The problem seems some Unicode character you introduced with copy-paste and is hard to spot.
 (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape (conf.py, line 259)

please check.

**Comment by kosl** [comment]
I can’t explain why l.256 fails.
Now I have just comment it out and fixed .PNG to .png.
You are using figure in a table with a caption. It should be:

.. figure: images/a.png

   Caption

Best regards, Leon

**Comment by Thrysoe** [comment]
It appears the issue was with moving from Sphinx v3 to v4.  Fixed in latest commit.

**Pull request merged**
